analytics_dashboard/courses/urls.py
# pylint: disable=no-value-for-parameter

from django.conf.urls import url, patterns, include

from courses import views
from courses.views import enrollment, engagement, performance, csv

CONTENT_ID_PATTERN = r'(?P<content_id>(?:i4x://?[^/]+/[^/]+/[^/]+/[^@]+(?:@[^/]+)?)|(?:[^/]+))'
COURSE_ID_PATTERN = r'(?P<course_id>[^/+]+[/+][^/+]+[/+][^/]+)'
PROBLEM_PART_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'problem_part_id')
ASSIGNMENT_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'assignment_id')
PROBLEM_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'problem_id')
SECTION_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'section_id')
SUBSECTION_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'subsection_id')
VIDEO_ID_PATTERN = CONTENT_ID_PATTERN.replace('content_id', 'video_id')
PIPELINE_VIDEO_ID = r'(?P<pipeline_video_id>([^/+]+[/+][^/+]+[/+][^/]+)+[|]((?:i4x://?[^/]+/[^/]+/[^/]+' \
                    r'/[^@]+(?:@[^/]+)?)|(?:[^/]+)+))'

answer_distribution_regex = \
    r'^graded_content/assignments/{assignment_id}/problems/{problem_id}/parts/{part_id}/answer_distribution/$'.format(
        assignment_id=ASSIGNMENT_ID_PATTERN, problem_id=PROBLEM_ID_PATTERN, part_id=PROBLEM_PART_ID_PATTERN)

ungraded_answer_distribution_regex = \
    r'^ungraded_content/sections/{}/subsections/{}/problems/{}/parts/{}/answer_distribution/$'.format(
        SECTION_ID_PATTERN, SUBSECTION_ID_PATTERN, PROBLEM_ID_PATTERN, PROBLEM_PART_ID_PATTERN)

video_timeline_regex = \
    r'^videos/sections/{}/subsections/{}/modules/{}/timeline/$'.format(
        SECTION_ID_PATTERN, SUBSECTION_ID_PATTERN, VIDEO_ID_PATTERN)

ENROLLMENT_URLS = patterns(
    '',
    url(r'^activity/$', enrollment.EnrollmentActivityView.as_view(), name='activity'),
    url(r'^geography/$', enrollment.EnrollmentGeographyView.as_view(), name='geography'),
    url(r'^demographics/age/$', enrollment.EnrollmentDemographicsAgeView.as_view(), name='demographics_age'),
    url(r'^demographics/education/$', enrollment.EnrollmentDemographicsEducationView.as_view(),
        name='demographics_education'),
    url(r'^demographics/gender/$', enrollment.EnrollmentDemographicsGenderView.as_view(), name='demographics_gender'),
)

ENGAGEMENT_URLS = patterns(
    '',
    url(r'^content/$', engagement.EngagementContentView.as_view(), name='content'),
    url(r'^videos/$', engagement.EngagementVideoCourse.as_view(), name='videos'),
    # ordering of the URLS is important for routing the the section, subsection, etc. correctly
    url(video_timeline_regex, engagement.EngagementVideoTimeline.as_view(), name='video_timeline'),
    url(r'^videos/sections/{}/subsections/{}/$'.format(SECTION_ID_PATTERN, SUBSECTION_ID_PATTERN),
        engagement.EngagementVideoSubsection.as_view(),
        name='video_subsection'),
    url(r'^videos/sections/{}/$'.format(SECTION_ID_PATTERN),
        engagement.EngagementVideoSection.as_view(),
        name='video_section'),
)

PERFORMANCE_URLS = patterns(
    '',
    url(r'^ungraded_content/$', performance.PerformanceUngradedContent.as_view(), name='ungraded_content'),
    url(ungraded_answer_distribution_regex, performance.PerformanceUngradedAnswerDistribution.as_view(),
        name='ungraded_answer_distribution'),
    url(r'^ungraded_content/sections/{}/subsections/{}/$'.format(SECTION_ID_PATTERN, SUBSECTION_ID_PATTERN),
        performance.PerformanceUngradedSubsection.as_view(),
        name='ungraded_subsection'),
    url(r'^ungraded_content/sections/{}/$'.format(SECTION_ID_PATTERN),
        performance.PerformanceUngradedSection.as_view(),
        name='ungraded_section'),
    url(r'^graded_content/$', performance.PerformanceGradedContent.as_view(), name='graded_content'),
    url(r'^graded_content/(?P<assignment_type>[\w-]+)/$',
        performance.PerformanceGradedContentByType.as_view(),
        name='graded_content_by_type'),
    url(answer_distribution_regex, performance.PerformanceAnswerDistributionView.as_view(), name='answer_distribution'),

    # This MUST come AFTER the answer distribution pattern; otherwise, the answer distribution pattern
    # will be interpreted as an assignment pattern.
    url(r'^graded_content/assignments/{}/$'.format(ASSIGNMENT_ID_PATTERN),
        performance.PerformanceAssignment.as_view(),
        name='assignment'),
)

CSV_URLS = patterns(
    '',
    url(r'^enrollment/$', csv.CourseEnrollmentCSV.as_view(), name='enrollment'),
    url(r'^enrollment/geography/$', csv.CourseEnrollmentByCountryCSV.as_view(), name='enrollment_geography'),
    url(r'^enrollment/demographics/age/$',
        csv.CourseEnrollmentDemographicsAgeCSV.as_view(),
        name='enrollment_demographics_age'),
    url(r'^enrollment/demographics/education/$',
        csv.CourseEnrollmentDemographicsEducationCSV.as_view(),
        name='enrollment_demographics_education'),
    url(r'^enrollment/demographics/gender/$',
        csv.CourseEnrollmentDemographicsGenderCSV.as_view(),
        name='enrollment_demographics_gender'),
    url(r'^engagement/activity_trend/$',
        csv.CourseEngagementActivityTrendCSV.as_view(),
        name='engagement_activity_trend'),
    url(r'^engagement/videos/{}/$'.format(PIPELINE_VIDEO_ID),
        csv.CourseEngagementVideoTimelineCSV.as_view(),
        name='engagement_video_timeline'),
    url(r'^performance/graded_content/problems/{}/answer_distribution/{}/$'.format(CONTENT_ID_PATTERN,
                                                                                   PROBLEM_PART_ID_PATTERN),
        csv.PerformanceAnswerDistributionCSV.as_view(),
        name='performance_answer_distribution'),
)

COURSE_URLS = patterns(
    '',
    # Course homepage. This should be the entry point for other applications linking to the course.
    url(r'^$', views.CourseHome.as_view(), name='home'),
    url(r'^enrollment/', include(ENROLLMENT_URLS, namespace='enrollment')),
    url(r'^engagement/', include(ENGAGEMENT_URLS, namespace='engagement')),
    url(r'^performance/', include(PERFORMANCE_URLS, namespace='performance')),
    url(r'^csv/', include(CSV_URLS, namespace='csv')),
)

urlpatterns = patterns(
    '',
    url('^$', views.CourseIndex.as_view(), name='index'),
    url(r'^{}/'.format(COURSE_ID_PATTERN), include(COURSE_URLS))
)

analytics_dashboard/urls.py
# pylint: disable=line-too-long,no-value-for-parameter
import os

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

# pylint suggests importing analytics_dashboard.core, which causes errors in our AMI
# pylint: disable=relative-import
from core import views


admin.autodiscover()

js_info_dict = {
    'packages': ('core', 'courses',),
}

urlpatterns = patterns(
    '',
    url(r'^$', views.LandingView.as_view(), name='landing'),
    url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', js_info_dict),
    url(r'^status/$', views.status, name='status'),
    url(r'^health/$', views.health, name='health'),
    url(r'^courses/', include('courses.urls', namespace='courses')),
    url(r'^admin/', include(admin.site.urls)),
    url('', include('social.apps.django_app.urls', namespace='social')),
    url(r'^accounts/login/$',
        RedirectView.as_view(url=reverse_lazy('social:begin', args=['edx-oidc']), permanent=False, query_string=True),
        name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout'),
    url(r'^accounts/logout_then_login/$', views.logout_then_login, name='logout_then_login'),
    url(r'^test/auto_auth/$', views.AutoAuth.as_view(), name='auto_auth'),
    url(r'^announcements/', include('announcements.urls')),
)

if settings.DEBUG:  # pragma: no cover
    urlpatterns += patterns(
        '',
        url(r'^403/$', 'django.views.defaults.permission_denied'),
        url(r'^404/$', 'django.views.defaults.page_not_found'),
        url(r'^500/$', 'django.views.defaults.server_error'),
        url(r'^503/$', views.ServiceUnavailableView.as_view()),
    )

    if os.environ.get('ENABLE_DJANGO_TOOLBAR', False):
        import debug_toolbar  # pylint: disable=import-error

        urlpatterns += patterns(
            '',
            url(r'^__debug__/', include(debug_toolbar.urls)),
        )

analytics_dashboard/core/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    """ Custom user model. """

    # TODO: it may not be necessary to store the language
    # preferences. Saving it in the session should be enough.
    language = models.CharField(max_length=255, null=True, choices=settings.LANGUAGES, default=None)

    @property
    def access_token(self):
        try:
            return self.social_auth.first().extra_data[u'access_token']  # pylint: disable=no-member
        except Exception:  # pylint: disable=broad-except
            return None

    class Meta(object):
        get_latest_by = 'date_joined'
        db_table = 'analytics_dashboard_user'   # Legacy table name

analytics_dashboard/django_rjs/models.py
# This app does not require any models.

analytics_dashboard/core/views.py
import json
import logging
import uuid

import django
from django.conf import settings
from django.contrib.auth import get_user_model, login, authenticate, REDIRECT_FIELD_NAME
from django.db import connection, DatabaseError
from django.http import HttpResponse, Http404
from django.shortcuts import redirect
from django.views.generic import View, TemplateView
from django.core.urlresolvers import reverse_lazy
from analyticsclient.client import Client
from analyticsclient.exceptions import ClientError

from analytics_dashboard.courses import permissions


logger = logging.getLogger(__name__)
User = get_user_model()


def status(_request):
    return HttpResponse()


def health(_request):
    OK = 'OK'
    UNAVAILABLE = 'UNAVAILABLE'

    overall_status = analytics_api_status = database_status = UNAVAILABLE

    try:
        cursor = connection.cursor()
        cursor.execute("SELECT 1")
        cursor.fetchone()
        cursor.close()
        database_status = OK
    except DatabaseError:  # pylint: disable=catching-non-exception
        database_status = UNAVAILABLE

    try:
        client = Client(base_url=settings.DATA_API_URL, auth_token=settings.DATA_API_AUTH_TOKEN)
        if client.status.healthy:
            analytics_api_status = OK
    except ClientError as e:
        logger.exception('API is not reachable from dashboard: %s', e)
        analytics_api_status = UNAVAILABLE

    overall_status = OK if (analytics_api_status == database_status == OK) else UNAVAILABLE

    data = {
        'overall_status': overall_status,
        'detailed_status': {
            'database_connection': database_status,
            'analytics_api': analytics_api_status
        }
    }

    return HttpResponse(json.dumps(data), content_type='application/json', status=200 if overall_status == OK else 503)


class AutoAuth(View):
    """
    Creates and authenticates a new User.

    If the setting ENABLE_AUTO_AUTH is not set to True, returns a 404.
    """

    def get(self, request, *_args, **_kwargs):
        if not settings.ENABLE_AUTO_AUTH:
            raise Http404

        if not settings.AUTO_AUTH_USERNAME_PREFIX:
            raise ValueError('AUTO_AUTH_USERNAME_PREFIX must be set!')

        # Create a new user
        username = password = settings.AUTO_AUTH_USERNAME_PREFIX + uuid.uuid4().hex[0:20]
        user = User.objects.create_user(username, password=password)

        # Grant user access to demo course
        permissions.set_user_course_permissions(user, ['edX/DemoX/Demo_Course'])

        # Login the new user
        user = authenticate(username=username, password=password)
        login(request, user)

        return redirect('/')


def logout(request, next_page='/', template_name=None,
           redirect_field_name=REDIRECT_FIELD_NAME, current_app=None, extra_context=None):
    """
    Revoke user permissions and logout
    """

    # Revoke permissions
    permissions.revoke_user_course_permissions(request.user)

    # Back to the standard logout flow
    return django.contrib.auth.views.logout(request, next_page, template_name, redirect_field_name, current_app,
                                            extra_context)


def logout_then_login(request, login_url=reverse_lazy('login'), current_app=None, extra_context=None):
    """
    Logout then login
    """
    permissions.revoke_user_course_permissions(request.user)
    return django.contrib.auth.views.logout_then_login(request, login_url, current_app, extra_context)


class ServiceUnavailableView(TemplateView):
    """
    Service unavailable error page requesting users to wait and reload the page.
    """
    template_name = "503.html"


class LandingView(TemplateView):
    """
    Displays a public landing page when users first come to the site.
    """
    template_name = "core/landing.html"

    def dispatch(self, request, *args, **kwargs):
        """ Non logged in users will be directed to the landing page. """
        if request.user.is_anonymous():
            return super(LandingView, self).dispatch(request, *args, **kwargs)
        else:
            return redirect('courses:index')

    def get_context_data(self, **kwargs):
        context = super(LandingView, self).get_context_data(**kwargs)
        context['research_url'] = settings.RESEARCH_URL
        context['open_source_url'] = settings.OPEN_SOURCE_URL
        context['show_research'] = settings.SHOW_LANDING_RESEARCH and settings.RESEARCH_URL
        audience_message_column_width = 6
        if context['show_research']:
            audience_message_column_width = 4
        context['audience_message_column_width'] = audience_message_column_width

        return context

analytics_dashboard/courses/views/csv.py
import datetime
import logging
import urllib

from django.http import HttpResponse

from waffle import switch_is_active
from analyticsclient.constants import data_format, demographic
from analyticsclient.client import Client

from courses.views import CourseView


logger = logging.getLogger(__name__)


class CSVResponseMixin(object):
    csv_filename_suffix = None

    # pylint: disable=unused-argument
    def render_to_response(self, context, **response_kwargs):
        response = HttpResponse(self.get_data(), content_type='text/csv', **response_kwargs)
        response['Content-Disposition'] = u'attachment; filename="{0}"'.format(self._get_filename())
        return response

    def get_data(self):
        raise NotImplementedError

    def _get_filename(self):
        course_key = self.course_key
        course_id = '-'.join([course_key.org, course_key.course, course_key.run])
        filename = u'{0}--{1}.csv'.format(course_id, self.csv_filename_suffix)
        return urllib.quote(filename)


class CourseEnrollmentDemographicsAgeCSV(CSVResponseMixin, CourseView):
    csv_filename_suffix = u'enrollment-by-birth-year'

    def get_data(self):
        return self.course.enrollment(demographic.BIRTH_YEAR, data_format=data_format.CSV),


class CourseEnrollmentDemographicsEducationCSV(CSVResponseMixin, CourseView):
    csv_filename_suffix = u'enrollment-by-education'

    def get_data(self):
        return self.course.enrollment(demographic.EDUCATION, data_format=data_format.CSV),


class CourseEnrollmentDemographicsGenderCSV(CSVResponseMixin, CourseView):
    csv_filename_suffix = u'enrollment-by-gender'

    def get_data(self):
        end_date = datetime.datetime.utcnow().strftime(Client.DATE_FORMAT)
        return self.course.enrollment(demographic.GENDER, end_date=end_date, data_format=data_format.CSV),


class CourseEnrollmentByCountryCSV(CSVResponseMixin, CourseView):
    csv_filename_suffix = u'enrollment-location'

    def get_data(self):
        return self.course.enrollment(demographic.LOCATION, data_format=data_format.CSV)


class CourseEnrollmentCSV(CSVResponseMixin, CourseView):
    csv_filename_suffix = u'enrollment'

    def get_data(self):
        _demographic = 'mode' if switch_is_active('display_verified_enrollment') else None
        end_date = datetime.datetime.utcnow().strftime(Client.DATE_FORMAT)
        return self.course.enrollment(_demographic, data_format=data_format.CSV, end_date=end_date)


class CourseEngagementActivityTrendCSV(CSVResponseMixin, CourseView):
    csv_filename_suffix = u'engagement-activity'

    def get_data(self):
        end_date = datetime.datetime.utcnow().strftime(Client.DATE_FORMAT)
        return self.course.activity(data_format=data_format.CSV, end_date=end_date)


class CourseEngagementVideoTimelineCSV(CSVResponseMixin, CourseView):
    csv_filename_suffix = u'engagement-video-timeline'

    def get_data(self):
        modules = self.client.modules(self.course_id, self.kwargs['pipeline_video_id'])
        return modules.video_timeline(data_format=data_format.CSV)


class PerformanceAnswerDistributionCSV(CSVResponseMixin, CourseView):
    csv_filename_suffix = u'performance-answer-distribution'

    def get_data(self):
        modules = self.client.modules(self.course_id, self.kwargs['content_id'])
        return modules.answer_distribution(data_format=data_format.CSV)

analytics_dashboard/help/views.py
from help import HELP_CONTEXT_TOKEN_NAME


class ContextSensitiveHelpMixin(object):
    """
    Adds page-specific data to enable context-sensitive help.
    """

    help_token = None

    def get_context_data(self, **kwargs):
        context = super(ContextSensitiveHelpMixin, self).get_context_data(**kwargs)
        context[HELP_CONTEXT_TOKEN_NAME] = self.help_token
        return context

analytics_dashboard/templates/_announcement.html
{% load i18n %}

<div class="announcement-container"
     data-dismiss-url="{{ dismiss_url }}"
     data-view="announcement">
    <div class="container">
        <div class="row">
            <div class="hidden-xs col-sm-1">
                <div class="icon"><i class="fa fa-bullhorn"></i></div>
            </div>

            <div class="col-xs-10">
                {% if message %}
                    {{ message|safe }}
                {% else %}
                    <div class="message">
                        <h1>{{ title }}</h1>
                        <p>{{ body|safe }}</p>
                    </div>
                {% endif %}
            </div>

            {% if dismiss_url %}
                <div class="col-xs-2 col-sm-1">
                    {% csrf_token %}
                    <a class="dismiss">
                        <span aria-hidden="true"><i class="fa fa-times"></i></span>
                        <span class="sr-only">{% trans "Close" %}</span>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</div>

analytics_dashboard/templates/announcements.html
{% load soapbox %}
{% load announcements_tags %}

{% get_messages_for_page view.page_name as soapbox_messages %}
{% for message in soapbox_messages %}
  {% include "_announcement.html" with message=message %}
{% endfor %}

{% announcements as announcements_list %}
{% with announcements_list|first as announcement %}
  {% if announcement %}
    {% include "_announcement.html" with body=announcement.content title=announcement.title dismiss_url=announcement.dismiss_url %}
  {% endif %}
{% endwith %}

analytics_dashboard/templates/base-error.html
{% extends "base_dashboard.html" %}

{% load i18n %}
{% load dashboard_extras %}

{% block view-name %}view-system{% endblock view-name %}

{# These are intentionally left blank. #}
{% block header %}{% endblock %}
{% block lens_navigation %}{% endblock %}
{% block announcements %}{% endblock %}
{% block footer %}{% endblock %}

{% block content-outer %}
  <div class="site-wrapper">

    <div class="site-wrapper-inner">

      <div class="cover-container">

        <div class="masthead clearfix">
          <div class="inner">
            {% include 'brand.html' with class_prefix='masthead' %}
          </div>
        </div>

        <div class="inner cover">
          <h1 class="cover-heading">
            <span class="error-code">{% block error-code %}{% endblock %}</span>
            <span class="error-title">{% block error-title %}{% endblock %}</span>
          </h1>

          <p class="lead error-copy">
              {% block error-copy %}
              If you continue to see this error, use the link below to contact our support team.
              {% endblock error-copy %}
          </p>

          <p class="lead">
            {% block buttons %}
              <a href="{% settings_value 'SUPPORT_URL' %}" class="btn btn-lg btn-primary" data-role="support-link" target="_blank"
                 title="{% trans 'Use our support tool to ask questions or share feedback.' %}">
                <i class="ico fa fa-life-ring" aria-hidden="true"></i>
                {% captureas platform_name %}{% settings_value "PLATFORM_NAME" %}{% endcaptureas %}

                {# Translators: This intention here is that a user clicks a button to contact a support group (e.g. edX Support, or MITx Support). Reorder the placeholder as you see fit. #}
                {% blocktrans %}Contact {{ platform_name }} Support{% endblocktrans %}
              </a>
            {% endblock %}
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

analytics_dashboard/templates/base.html
{% comment %}
Base template pages.
{% endcomment %}

{% load staticfiles %}
{% load compress %}
{% load dashboard_extras %}

<!DOCTYPE html>
<!--[if lte IE 9]><html class="no-js lt-ie10" lang="en"><![endif]-->
<!--[if gt IE 9]><!--><html class="no-js" lang="en"><!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>{% block title %}| {% settings_value 'FULL_APPLICATION_NAME' %}{% endblock title %}</title>

    {% comment %}
    The stylesheets can be either overriden or augmented here.  Make sure to use the block.super if you're
    adding additional stylesheets in your page when extending the base.
    {% endcomment %}

    {% block stylesheets %}
    {% compress css %}
      <link rel="stylesheet" href="{% static 'sass/style-application.scss' %}" type="text/x-scss">
      {% captureas theme_scss %}
        {% settings_value 'THEME_SCSS' %}
      {% endcaptureas %}
      <link rel="stylesheet" href="{% static theme_scss %}" type="text/x-scss">
    {% endcompress %}
    {% endblock %}

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

</head>

{% block body %}{% endblock %}
</html>

analytics_dashboard/templates/base_dashboard.html
{% extends "base.html" %}


{% load i18n %}
{% load staticfiles %}
{% load compress %}
{% load dashboard_extras %}
{% load rjs %}


{% block body %}
  <body class="{% block view-name %}{% endblock view-name %}">
  <div id="wrap-content-push-footer-sock">
    {% block header %}
      {% include "header.html" %}
    {% endblock header %}

    {% block announcements %}
      {% include "announcements.html" %}
    {% endblock %}

    {% block lens_navigation %}
      {% include "lens-navigation.html" %}
    {% endblock lens_navigation %}

    <div class="container">
      <div class="row">
        {% block content-outer %}
          {#  Translators: Application here refers to the web site/application being used (e.g. the dashboard). #}
          <main class="col-xs-12 main" id="content" aria-label="{% trans "Application" %}">
            <div class="view-head">
              {% block header-text %}
                {% if page_title %}
                  <div class="row page-title-outer">
                    <div class="col-md-6 col-xs-12">
                      <h1>{{ page_title }}</h1>
                    </div>
                    <div class="col-md-6 col-xs-12">
                      <div class="page-subtitle">{{ page_subtitle|default_if_none:'' }}</div>
                    </div>
                  </div>
                {% endif %}
              {% endblock %}
            </div>

            <div class="view-intro">
              <p class="lead text-muted intro-text">
                {% block intro-text %}{% endblock intro-text %}
              </p>
            </div>

            {% block content %}
            {% endblock content %}
          </main>
        {% endblock %}
      </div>
    </div>

    <!-- Placed at the end of the document so the pages load faster -->
    {% comment %}
    Make sure to add your JS files here.  You'll probably want to use block.super to add to the comment includes rather
    than override them.
    {% endcomment %}

    {# Translation support for JavaScript strings. #}
    <script type="text/javascript" src="{% url 'django.views.i18n.javascript_catalog' %}"></script>
    <script type="text/javascript">
      window.language = "{{ LANGUAGE_CODE }}";
    </script>

    {# Initial page data passed from view to JS initializer #}
    {% if page_data %}
      <script type="text/javascript">
        var initModelData = {{ page_data|safe }};
      </script>
    {% endif %}

    {% compress js %}
      <script src="{% static 'bower_components/requirejs/require.js' %}"></script>
      <script src="{% static_rjs 'js/config.js' %}"></script>

      {# Note: django-compressor does not recognize the data-main attribute. Load the main script separately. #}
      <script src="{% static_rjs 'js/common.js' %}"></script>
    {% endcompress %}


    {% compress js %}
      {# Note: This block is purposely separated from the one above so that browsers cache the common JS instead of downloading a single, large file for each page. #}
      {% block javascript %}
      {% endblock javascript %}
    {% endcompress %}

    <div id="footer-sock-push"></div>
  </div>
  {% block footer %}
    <div id="footer-sock">
      {% include "footer.html" with show_feedback=True %}
    </div>
  {% endblock footer %}
  </body>
{% endblock body %}

analytics_dashboard/templates/brand.html
{% load staticfiles %}
{% load i18n %}
{% load dashboard_extras %}

<a class="{{ class_prefix }}-brand" href="/">
  <div class="{{ class_prefix }}-brand-logo" alt="{% settings_value 'PLATFORM_NAME' %}"></div>
  <span class="{{ class_prefix }}-brand-app">{% settings_value 'APPLICATION_NAME' %}</span>
</a>

analytics_dashboard/templates/header.html
{% load i18n %}
{% load firstof from future %}

{% comment %}
Partial: App-wide header element
{% endcomment %}

<header class="navbar navbar-default" role="banner" aria-label="main" id="nav">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav">
        <span class="sr-only">{% trans 'Toggle navigation' %}</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      {% include 'brand.html' with class_prefix='navbar' %}
      {% if course_id %}
      <ul class="nav navbar-nav">
        <li>
          <a href="{% url 'courses:home' course_id=course_id %}" class="navbar-link active-course-name">{% firstof course_name course_id %}</a>
        </li>
      </ul>
      {% endif %}
    </div>

    <div class="collapse navbar-collapse" id="main-nav">
      <ul class="nav navbar-nav navbar-right">
        {% if help_url %}
          <li>
            <a id="help" class="navbar-link " data-track-type="click" data-track-event="edx.bi.help.clicked"
               href="{{ help_url }}" target="_blank">{% trans "Help" %}</a>
          </li>
        {% endif %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle active-user navbar-link" data-toggle="dropdown" role="button"
             id="userMenu">
            <i class="ico-user fa fa-graduation-cap" aria-hidden="true"></i>
            <span class="active-user-name">{{ request.user.username }}</span>
            <i class="ico ico-indicator fa fa-caret-down"></i>
          </a>

          <ul class="dropdown-menu active-user-nav" role="menu" aria-labelledby="userMenu">
            <li>
              <a class="active-user-nav-logout" href="{% url 'logout' %}">{% trans "Logout" %}</a>
            </li>
          </ul>
        </li>
      </ul>
    </div>
    <!-- / navbar-collapse -->
  </div>
  <!-- / container -->
</header>
<!-- / navbar -->